---
- name: Ensure configured homebrew casks are installed.
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_homebrew: no
    install_options: "{{ item.options | default([]) }}"
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ macos_homebrew.install.cask }}"
  with_items: "{{ macos_homebrew.casks | default([]) }}"
