---
- name: Determine installed casks
  command: 'brew cask list'
  register: brew_cask
  when: macos_homebrew.casks
  changed_when: false

- name: Ensure configured homebrew casks are installed.
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_homebrew: no
    install_options: "{{ item.options | default([]) }}"
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ macos_homebrew.install.cask }}"
  with_items: "{{ macos_homebrew.casks | default([]) }}"
  when:
    - macos_homebrew.casks
    - item.name not in brew_cask.stdout_lines
  register: macos_homebrew_casks
  failed_when:
    - macos_homebrew_casks.msg
    - "'No Cask with this name exists' not in macos_homebrew_casks.msg"
    - "'Cask installed' not in macos_homebrew_casks.msg"
