---
- name: Setup homebrew install path.
  become: true
  file:
    path: "{{ macos_homebrew.install.path }}"
    group: admin
    mode: 0775
    state: directory

- name: Check if homebrew binary is already in place.
  stat: "path={{ macos_homebrew.install.bin }}/brew"
  register: homebrew_binary

- name: Ensure homebrew is installed.
  become: true
  shell: creates={{ macos_homebrew.install.bin }}/brew curl -fsSL https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C {{ macos.homebrew.install.path }}
  when: homebrew_binary.stat.exists == false

- name: Ensure permissions on macos_homebrew.install.path dirs.
  become: true
  file:
    path: "{{ macos_homebrew.install.path }}"
    group: admin
    mode: 0775
    state: directory
    recurse: true
  when: homebrew_binary.stat.exists == false

- name: Check if homebrew binary is already in place.
  stat: "path={{ macos_homebrew.install.bin }}/brew"
  register: homebrew_binary

- name: Symlink brew to macos_homebrew.install.bin.
  file:
    src: "{{ macos_homebrew.install.path }}/bin/brew"
    dest: "{{ macos_homebrew.install.bin }}/brew"
    state: link
  when: homebrew_binary.stat.exists == false
  become: true

- name: Update homebrew
  homebrew:
    update_homebrew: yes
