---
- name: Ensure correct permissions
  become: true
  file:
    path: "/usr/local/bin"
    state: directory
    owner: "{{ ansible_user_id }}"
    recurse: true

- name: Check if homebrew binary is already in place.
  stat:
    path: '{{ macos_homebrew.install.prefix }}/{{ macos_homebrew.install.path }}/bin/brew'
  register: homebrew_binary

- name: Install homebrew
  shell: 'echo "\n" | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  when: homebrew_binary.stat.exists == false

- name: Force update after installation.
  command: 'brew update --force'
  when: homebrew_binary.stat.exists == false
