---
- name: Cleanup homebrew packages
  command: "brew cleanup"
  ignore_errors: true
  changed_when: false
  when: homebrew_binary.stat.exists == false

- name: Cleanup cask packages
  command: "brew cask cleanup"
  ignore_errors: true
  changed_when: false
  when: homebrew_binary.stat.exists == false
